Add server test startup to systemd sanity check
Running mysqld --verbose --help will produce helpful errors
for issues such as invalid configuration options, which can be shown
on the service status page so users do not need to dig through the
server log.

diff --git a/debian/additions/mysql-systemd-start b/debian/additions/mysql-systemd-start
--- a/debian/additions/mysql-systemd-start
+++ b/debian/additions/mysql-systemd-start
@@ -34,6 +34,21 @@ sanity () {
     echo "MySQL system database not found in ${datadir}. Please run mysqld --initialize."
     exit 1
   fi
+
+  # Do a test start to make sure there are no configuration issues or similar
+  # mysqld --verbose --help will output a full listing of settings and plugins.
+  # To do so it needs to initialize the database, so it can be used as a test
+  # for whether or not the server can start. We redirect stdout to /dev/null so
+  # only the error messages are left.
+  result=0
+  output=$(mysqld --verbose --help --innodb-read-only 2>&1 > /dev/null) || result=$?
+  if [ ! "$result" = "0" ]; then
+    echo "ERROR: Unable to start MySQL server:" >&2
+    echo "$output" >&2
+    echo "Please take a look at https://wiki.debian.org/Teams/MySQL/FAQ for tips on fixing common upgrade issues." >&2
+    echo "Once the problem is resolved, restart the service." >&2
+    exit 1
+  fi
 }
 
 case $1 in
